### ISSUE TITLE
Integrar sistema con AWS

### ISSUE THREAD

**Issue by fedesanches** [apollo-utn-frd/apollo#10]
Hay que probar con una cuenta gratis, por lo menos para salir del paso y ver como funciona. Si alguna tiene tarjeta de crédito para probar, bienvenido sea. La mía no anduvo(?

**Comment by juanbono** [comment]
@matiasm15 esta la podemos cerrar ahora que usamos heroku? o deberiamos dejarla abierta por el frontend? @fedesanches

**Comment by matiasm15** [comment]
Lo deje por el front end. Estaria bueno subirlo a Amazon para aprender pero
siempre termine GGeado cuando quise crear la cuenta.

2018-01-04 10:28 GMT-03:00 Juan Bono <notifications@github.com>:
