### ISSUE TITLE
Actualizar a Angular 4

### ISSUE THREAD

**Issue by juanbono** [apollo-utn-frd/apollo#28]
Actualizar las dependencias y el codigo del frontend a Angular 4. Hay varias features nuevas asi que hay que ver como utilizarlas para mayor provecho!

**Comment by juanbono** [comment]
ahora vamos a usar reason-react asi que ... (?)

**Comment by matiasm15** [comment]
😎

2018-01-04 10:29 GMT-03:00 Juan Bono <notifications@github.com>:
